### ISSUE TITLE
assignment-servers 중복된 줄

### ISSUE THREAD

**Issue by gyusang** [wafflestudio/rookies#339]
@pullup-dip-burpee #302 에서 추가된
https://github.com/wafflestudio/rookies/blob/9bfc5ffd836e304cb5081a2c86dafddf714cc129/backend/seminar4/assignment-servers.md#L92-L97
줄이 #281 에서 추가된
https://github.com/wafflestudio/rookies/blob/9bfc5ffd836e304cb5081a2c86dafddf714cc129/backend/seminar4/assignment-servers.md#L84-L90
과 중복됩니다.
Merge 과정에서 #329 와 충돌이 있었던 것으로 보입니다.

**Comment by pullup-dip-burpee** [comment]
아 그렇군요 삭제하겠습니다!
